### ISSUE TITLE
Problèmes avec le champ heure

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1187]
- Champ durée différent du champ heure ?
- Autoriser à ne pas mettre les deux points sur la durée à la saisie ou mettre un champ heure ? 
- Peut-être que plutôt que durée on pourrait avoir un champ heure de fin

**Comment by alexandresoro** [comment]
Code pointer: https://github.com/alexandresoro/ouca/blob/9db528b1df9211172daa245cf0ecf55c3e7580d4/packages/common/src/api/inventory.ts#L53

Currently `duration` is a plain `varchar` on database.
Discuss what do we want to store + how.
Discuss what to do with user input on UI e.g. `12:34`, `1234`, `35`, `135`, `90`...

**Comment by alexandresoro** [comment]
Solution discussed:
- Allow `HH:mm`, `HHhmm` and `HHHmm` formats - like legacy app as input
- Also allow a plain number as input. In that case, it will be interpreted as number of minutes
- Store this as `HH:mm` in database regardless on how it's stored

It's ok that the field will be displayed with that format on view/update regardless of the format that was used initially.

Improvement:
Implement this in a way where migration to a plain number of minutes in DB could be done as next step

**Comment by alexandresoro** [comment]
Flagging as big as this would be a blocker for prod release
