### ISSUE TITLE
Saisie d'une observation: Erreur quand on renseigne plusieurs fois le même comportement ou milieu

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1189]
Il faudrait : 
- soit afficher une erreur plus parlante côté UI
- soit ne pas le permettre au niveau UI
- soit filtrer les doublons avant insert en DB
- soit l'autoriser au niveau de la DB

{statusCode: 500, error: "Internal Server Error",…}
error
: 
"Internal Server Error"
message
: 
"Query violates a unique integrity constraint. duplicate key value violates unique constraint \"idx_16490_primary\""
statusCode
: 
500

**Comment by alexandresoro** [comment]
Adding a check on the shared upsert entry input fixes the issue quite cleanly:
- backend will reject any input that contain duplicates environments or behaviors
- on ui side, the form is considered as invalid and disabled whenever duplicates are present

It could be improved by displaying something around the error location on UI side, but this is a separate topic as we don't do that anywhere currently.
