### ISSUE TITLE
Commune: Edition: afficher une erreur quand on renseigne un code commune qui n'est pas un nombre

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1218]

**Comment by alexandresoro** [comment]
Whenever the town code is invalid, the input is now red since https://github.com/alexandresoro/ouca/commit/684c9b0b24699101d8726f8171861c8972b29a89 . 
Is that OK enough to close it?
We could add a message, but I'd like to tackle this improvement globally instead of field by field if expected.

**Comment by camillecarrier** [comment]
LGTM 👍
