### ISSUE TITLE
Multi-selecteur: afficher les valeurs sélectionnées en noir

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1233]
De la même couleur que les valeurs des autres champs

**Comment by alexandresoro** [comment]
Currently the selection uses the placeholder info.
Hence the color.
That's a ugly workaround to display the current selection in a compact way.

We can't set this as input because it would render the autocomplete unusable.

Need to discuss to redesign the autocomplete IMO.

**Comment by alexandresoro** [comment]
Autocomplete w/ multiple selection has been redesigned in https://github.com/alexandresoro/ouca/commit/f371b36960c58705467208208f3857f431a9cc72
Now, selected values are in their own chips - that should make this issue not relevant anymore.
