### ISSUE TITLE
Altitude (référentiel et inventaire): une erreur est remontée par le backend si on met une valeur non entière

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1235]
Mieux gérer l'erreur pour qu'elle soit claire pour l'utilisateur

**Comment by alexandresoro** [comment]
I did not manage to reproduce it.
Needs more context.

**Comment by camillecarrier** [comment]
<img width="865" alt="Capture d’écran 2023-08-12 à 08 17 23" src="https://github.com/alexandresoro/ouca/assets/51759833/531b3c7d-ae62-49ea-91f3-1ed04ed73f75">
