### ISSUE TITLE
Frontend:  Highlight the focused input

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1614]
Find a way to show which input has the focus.

**Comment by alexandresoro** [comment]
Checked offline. Seems only to occur w/ localities edit - an only the first time the popup is opened.

We can see in the console `There are no focusable elements inside the <FocusTrap />`

It only happens on `<LieuDitEdit />` when included from `<LieuDitUpdate />`.
It looks related to the query that needs to be performed here: https://github.com/alexandresoro/ouca/blob/4b96a379f79683bd60b01bb57548d5de8bc8093e/packages/frontend/src/features/manage/lieu-dit/LieuDitUpdate.tsx#L68
By removing these conditions, we have a proper focus.

**Comment by alexandresoro** [comment]
Fixed with https://github.com/alexandresoro/ouca/commit/620b7ed7cb088cb3bc41638e1291e242debb264c
